# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Python package

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Flask
        run: pip install flask
      - name: Install SQL
        run: pip install flask_sqlalchemy
      - name: Testes usuarios
        run: |
          python -m unittest tests/test_usuario.py
      - name: Testes unidades Bibliotecas
        run: |
          python -m unittest tests/test_unidadeBiblioteca.py
      - name: Testes livros
        run: |
          python -m unittest tests/test_livro.py
      - name: Testes emprestimos
        run: |
          python -m unittest tests/test_emprestimo.py
      - name: Testes livroBiblioteca
        run: |
          python -m unittest tests/test_livroBiblioteca.py
      - name: Install Coverage.py
        run: pip install coverage
      - name: Run coverage
        run: coverage run -m unittest discover
      - uses: codecov/codecov-action@v2
        with:
          files: htmlcov/index.html
          flags: unittests
          name: Publish coverage to Codecov
